name: WorldControl
version: 1.2.2
main: dev.acri.worldcontrol.Main
author: Viktoracri

commands:
  control:
    description: Access the WorldControl GUI
    aliases: [wc, worldcontrol, wcontrol]